#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Add . and $HOME/bin to path
path=(
  .
  $HOME/bin
  $path
)

# Editors
export EDITOR='vim'
export VISUAL='vim'

# Initialize LMOD for modules
. /usr/local/opt/lmod/init/zsh
export OPT=/opt/modules
export JEDI_OPT=$OPT
module use -a $OPT/modulefiles/core
module use -a $OPT/modulefiles/apps

# Auto extension stuff
alias -s c=$EDITOR
alias -s cc=$EDITOR
alias -s f90=$EDITOR
alias -s java=$EDITOR
alias -s php=$EDITOR
alias -s html=$BROWSER
alias -s htm=$BROWSER

# Set user-defined aliases
test -e "${HOME}/.bash_aliases" && source "${HOME}/.bash_aliases"

# Add iterm2 shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
